BUS_RESV:main.o front_page.o Sign_In.o Sign_Up.o Seat_Reservation.o display.o Save_Reservation.o
	cc main.o front_page.o Sign_In.o Sign_Up.o Seat_Reservation.o display.o Save_Reservation.o -o BUS_RESV

main.o:main.c
	cc -c main.c

front_page.o:front_page.c
	cc -c front_page.c

Sign_In.o:Sign_In.c
	cc -c Sign_In.c

Sign_Up.o:Sign_Up.c
	cc -c Sign_Up.c

Seat_Reservation.o:Seat_Reservation.c
	cc -c Seat_Reservation.c

Save_Reservation.o:Save_Reservation.c
	cc -c Save_Reservation.c

display.o:display.c
	cc -c display.c


